"use strict";

const fs = require("fs");
const path = require("path");
const https = require("https");

function resolveInputOutput() {
    const args = process.argv.slice(2);
    if (args.length === 2) {
        return {
            inputFile: path.resolve(process.cwd(), args[0]),
            outputFile: path.resolve(process.cwd(), args[1])
        };
    }
    if (args.length !== 0) {
        throw new Error("Usage: node generateLocaleQuotesCs.js [localeDefs.json LocaleQuotesGenerated.cs]");
    }
    return {
        inputFile: path.resolve(__dirname, "../../Lib/ToolsDir/localeDefs.json"),
        outputFile: path.resolve(__dirname, "../../Lib/ToolsDir/LocaleQuotesGenerated.cs")
    };
}

function normalizeLocale(locale) {
    return locale.toLowerCase();
}

function toCldrLocale(locale) {
    return locale.split("-").map((part, index) => {
        if (index === 0) return part.toLowerCase();
        if (part.length === 4) return part[0].toUpperCase() + part.slice(1).toLowerCase();
        if (part.length === 2 || /^\d{3}$/.test(part)) return part.toUpperCase();
        return part.toLowerCase();
    }).join("-");
}

function fetchText(url) {
    return new Promise((resolve, reject) => {
        const request = https.get(url, response => {
            if (response.statusCode >= 300 && response.statusCode < 400 && response.headers.location) {
                response.resume();
                fetchText(response.headers.location).then(resolve, reject);
                return;
            }
            if (response.statusCode === 404) {
                response.resume();
                resolve(null);
                return;
            }
            if (response.statusCode !== 200) {
                response.resume();
                reject(new Error(`HTTP ${response.statusCode} for ${url}`));
                return;
            }
            const chunks = [];
            response.setEncoding("utf8");
            response.on("data", chunk => chunks.push(chunk));
            response.on("end", () => resolve(chunks.join("")));
        });
        request.on("error", reject);
    });
}

async function fetchDelimitersExact(locale, cache) {
    if (cache.has(locale)) return cache.get(locale);

    const cldrLocale = toCldrLocale(locale);
    const url =
        `https://raw.githubusercontent.com/unicode-org/cldr-json/main/cldr-json/cldr-misc-full/main/${cldrLocale}/delimiters.json`;
    const text = await fetchText(url);
    if (text == null) {
        cache.set(locale, null);
        return null;
    }
    const json = JSON.parse(text);
    const delimiters = json.main[cldrLocale].delimiters;
    const result = {
        openQuote: delimiters.quotationStart,
        closeQuote: delimiters.quotationEnd
    };
    cache.set(locale, result);
    return result;
}

async function resolveDelimiters(locale, cache, defaultQuotes) {
    let current = normalizeLocale(locale);
    while (true) {
        const delimiters = await fetchDelimitersExact(current, cache);
        if (delimiters != null) return delimiters;
        const dashIndex = current.lastIndexOf("-");
        if (dashIndex < 0) return defaultQuotes;
        current = current.substring(0, dashIndex);
    }
}

function quoteKey(delimiters) {
    return `${delimiters.openQuote}\u001f${delimiters.closeQuote}`;
}

function escapeCSharpString(value) {
    return value
        .replace(/\\/g, "\\\\")
        .replace(/"/g, "\\\"");
}

function buildGeneratedFile(groups) {
    const cases = groups.map(group => {
        const labels = group.locales.map(locale => `            case "${locale}":`).join("\n");
        return `${labels}\n                openQuote = "${escapeCSharpString(group.openQuote)}";\n                closeQuote = "${escapeCSharpString(group.closeQuote)}";\n                return true;`;
    }).join("\n");

    return `// <auto-generated />
#nullable enable

namespace Lib.ToolsDir;

internal static class LocaleQuotesGenerated
{
    public static bool TryGetExactQuotes(string locale, out string openQuote, out string closeQuote)
    {
        switch (locale)
        {
${cases}
            default:
                openQuote = "";
                closeQuote = "";
                return false;
        }
    }
}
`;
}

async function main() {
    const paths = resolveInputOutput();
    const localeDefs = JSON.parse(fs.readFileSync(paths.inputFile, "utf8"));
    const locales = Object.keys(localeDefs).map(normalizeLocale).sort();
    const cache = new Map();
    const defaultQuotes = await resolveDelimiters("en", cache, { openQuote: "\"", closeQuote: "\"" });
    const reduced = new Map();

    for (const locale of locales) {
        const delimiters = await resolveDelimiters(locale, cache, defaultQuotes);
        const dashIndex = locale.lastIndexOf("-");
        if (dashIndex >= 0) {
            const parentLocale = locale.substring(0, dashIndex);
            const parentDelimiters = await resolveDelimiters(parentLocale, cache, defaultQuotes);
            if (quoteKey(delimiters) === quoteKey(parentDelimiters)) continue;
        }
        reduced.set(locale, delimiters);
    }

    const grouped = new Map();
    for (const [locale, delimiters] of reduced) {
        const key = quoteKey(delimiters);
        let group = grouped.get(key);
        if (group == null) {
            group = { openQuote: delimiters.openQuote, closeQuote: delimiters.closeQuote, locales: [] };
            grouped.set(key, group);
        }
        group.locales.push(locale);
    }

    const groups = Array.from(grouped.values())
        .map(group => ({
            openQuote: group.openQuote,
            closeQuote: group.closeQuote,
            locales: group.locales.sort()
        }))
        .sort((a, b) => a.locales[0].localeCompare(b.locales[0]));

    fs.writeFileSync(paths.outputFile, buildGeneratedFile(groups));
    console.log(`Generated ${path.relative(process.cwd(), paths.outputFile)} with ${reduced.size} exact locales in ${groups.length} quote groups`);
}

main().catch(err => {
    console.error(err.stack || String(err));
    process.exitCode = 1;
});
