// <auto-generated />
#nullable enable

namespace Lib.ToolsDir;

internal static class LocaleQuotesGenerated
{
    public static bool TryGetExactQuotes(string locale, out string openQuote, out string closeQuote)
    {
        switch (locale)
        {
            case "af":
            case "az":
            case "bn":
            case "bo":
            case "cy":
            case "da":
            case "dv":
            case "en":
            case "eo":
            case "es":
            case "fil":
            case "fo":
            case "fy":
            case "ga":
            case "gd":
            case "gl":
            case "gu":
            case "hi":
            case "id":
            case "jv":
            case "km":
            case "kn":
            case "ko":
            case "ku":
            case "lo":
            case "lv":
            case "me":
            case "mi":
            case "ml":
            case "mn":
            case "mr":
            case "ms":
            case "mt":
            case "my":
            case "ne":
            case "pt":
            case "sd":
            case "si":
            case "sq":
            case "ss":
            case "sw":
            case "ta":
            case "te":
            case "tet":
            case "tg":
            case "th":
            case "tk":
            case "tlh":
            case "tr":
            case "tzl":
            case "tzm":
            case "uz":
            case "vi":
            case "yo":
                openQuote = "“";
                closeQuote = "”";
                return true;
            case "ar":
            case "ur":
                openQuote = "”";
                closeQuote = "“";
                return true;
            case "be":
            case "bm":
            case "br":
            case "ca":
            case "cv":
            case "el":
            case "es-us":
            case "eu":
            case "fa":
            case "fr":
            case "it":
            case "kk":
            case "ky":
            case "nb":
            case "nn":
            case "ru":
            case "uk":
                openQuote = "«";
                closeQuote = "»";
                return true;
            case "bg":
            case "cs":
            case "de":
            case "et":
            case "hr":
            case "is":
            case "ka":
            case "lb":
            case "lt":
            case "mk":
            case "sk":
            case "sl":
                openQuote = "„";
                closeQuote = "“";
                return true;
            case "bs":
            case "hu":
            case "pl":
            case "ro":
            case "sr":
                openQuote = "„";
                closeQuote = "”";
                return true;
            case "fi":
            case "he":
            case "se":
            case "sv":
                openQuote = "”";
                closeQuote = "”";
                return true;
            case "ja":
                openQuote = "「";
                closeQuote = "」";
                return true;
            case "nl":
                openQuote = "‘";
                closeQuote = "’";
                return true;
            default:
                openQuote = "";
                closeQuote = "";
                return false;
        }
    }
}
